trigger: none

parameters:
- name: environment
  displayName: Deployment Environment
  type: string
  default: dev
  values:
  - dev
  - test
  - prod


variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'mat-devops-${{ parameters.environment }}'
  location: 'uksouth'
  resourceGroupName: 'rg-logicapp-${{ parameters.environment }}'
  logicAppName: 'logicapp-matlogicapp-${{ parameters.environment }}'

stages:
- stage: 'infra_deploy'
  displayName: 'Deploy Infra to ${{ parameters.environment }} '
  jobs:
  - deployment: 'deploy_bicep'
    displayName: 'Deploy ${{ parameters.environment }} Infra Job'
    pool:
      vmImage: $(vmImageName)
    environment: 
      name: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: 'Azure CLI Deploy logicapp'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az deployment group create --name logicappdeploy -g $(resourceGroupName) --template-file bicep/logicapp.bicep --parameters environment=${{ parameters.environment }}

- stage: 'logicapp_workflow_deploy'
  displayName: 'Deploy Logic app Workflow to ${{ parameters.environment }} '
  jobs:
  - deployment: 'deploy_workflow'
    displayName: 'Deploy ${{ parameters.environment }} workflow Job'
    pool:
      vmImage: $(vmImageName)
    environment: 
      name: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: ArchiveFiles@2
            displayName: 'Create workflows ZIP'
            inputs: 
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/logic-app/$(Build.BuildId).zip'
              replaceExistingArchive: true

          - task: AzureFunctionApp@1
            displayName: 'Deploy workflows to Function App'
            inputs:
              azureSubscription: $(azureServiceConnection)
              appName: '$(logicAppName)'
              appType: 'workflowapp'
              package: '$(Build.ArtifactStagingDirectory)/logic-app/$(Build.BuildId).zip'
              deploymentMethod: 'zipDeploy'     

            